global using System.IO;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Input;
global using System.Windows.Media;
global using System.Windows.Media.Imaging;
global using System.Windows.Navigation;
global using System.Security.Permissions;
global using System.Windows.Threading;
global using static System.Convert;
global using System.ComponentModel;
