global using System.IO;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Input;
global using System.Windows.Media;
global using System.Windows.Navigation;
global using System.Windows.Threading;
global using static System.Convert;
global using System.Collections.ObjectModel;
global using System.Globalization;
global using System.Windows.Media.Animation;
global using System.Windows.Documents;
global using System.Windows.Shapes;
global using System.Windows.Data;
global using System.Windows.Media.Effects;